config/routes.rb
Rails.application.routes.draw do

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    '/home'   => 'users#home'
  root   'users#new'
  
  resources :requests
  resources :users

  resources :users do
  	resources :requests
  end 	

  resources :requests do
    resources :comments
  end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :request
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :requests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  helper_method :singlelogged_in?

  def singlelogged_in?
	session[:login]
  end

  private
  def authenticate
	login = authenticate_or_request_with_http_basic do |username, password|
	username == "username" && password == "password"
  end
	session[:login] = login
  end

  def do_logout
	session[:login] = nil
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create 
  	@request = Request.find(params[:request_id])
  	@comment = @request.comments.create(comments_params)
  	flash[:notice] = "Comment has been created"
  	redirect_to request_path(@request) 
  end 	

  def destroy
  	@request = Request.find(params[:request_id])
  	@request.comments.destroy
  	flash[:notice] = "Comment has been deleted"
  	redirect_to request_path(@request) 
  end
  
  private 

  def comments_params 
  	params.require(:comment).permit(:name, :body)
  end 	

end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home 
  end 
   
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, :only => [:index]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @user = User.find(params[:user_id])
    @request = @user.requests.create(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @user = User.find(params[:user_id])
    @user.requests.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:title, :username, :description, :status)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid username/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end

private

  def user_params
      params.require(:user).permit(:username, :password_digest)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def home 

  end   

  def index
  	@users = User.all
  end 	

  def show
    @requests = Request.all
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user  
        redirect_to @user
    else
      render 'new'
    end
  end

  def update 
    @user.update(user_params)
    redirect_to @user
  end   

  def destroy
  end

  private

    def set_user
      @user = User.find(params[:id])
    end  

    def user_params
      params.require(:user).permit(:username, :password, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TickettingSystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-default navbar-static-top">
		<div class="container">
			<% if logged_in? %>
			<a href="/home" class="navbar-brand">Customer Support</a>
			<% else %>
			<a href="/login" class="navbar-brand">Customer Support</a>
			<% end %>
			<ul class="nav navbar-nav">
				<% if logged_in? %>
				<li class="active"> <%= link_to "Log out", logout_path, method: "delete" %></li>
				<li><%= link_to 'profile', current_user %></li>
				<% else %>
				<li class="active"><a href="/login"> Login </a></li>
				<% end %>
			</ul>
		</div>
	</nav>	
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= react_component('HomePage') %>

app/views/requests/_form.html.erb
<%= form_for(request) do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.check_box :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.title %></td>
        <td><%= request.status? ? "\u2713" : "\u2717"  %></td>
        <td><%= request.description %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<div class="col-md-6">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        </button>
        <h4 class="modal-title"><%= @request.title %></h4>
        <button type="button" class="btn btn-default float-right" data-toggle="modal" data-target="#myModal"> Edit </button>
        <button type="button" class="btn btn-warning float-right" data-toggle="modal" data-target="#myModal1"> Close Issue </button>
      </div>
      <div class="modal-body">
        <p><%= @request.description %></p>
      </div>
      <div class="col-md-12">
      <h5>Comments</h5>
      	<%= form_for [@request, @request.comments.build] do |f| %>
      	<%= f.text_field :name %>
      </div>
      <div class="col-md-12">
      	<%= f.text_area :body  %><br>
      	<%= f.submit %>
      	<% end %>
      </div>
      <% @request.comments.each do |c| %>
      <div class="col-md-12">
      	<hr>
      	<%= c.name %><br>
      	<%= c.body %>
      	<hr>
      </div>	
      <% end %>
      <div class="modal-footer">
      </div>
    </div><!-- /.modal-content -->

    <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	    <div class="modal-dialog">
	      <div class="modal-content">
  		    <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	          <h4 class="modal-title" id="myModalLabel">Edit Issue</h4>
	        </div>
	        <div class="container">
		        <%= form_for @request do |f| %>
		        	<div class="form-group col-xs-3 row">
		        	<%= f.text_field :title, class: "form-control" %>
		        	</div>
		        	<div class="form-group col-xs-3 row">
		        	<%= f.text_area :description, class: "form-control" %>
		            </div>
		    </div>
	        <div class="modal-footer">
	        		<%= f.submit 'Update', class: 'btn btn-default btn-xs' %>
	        	<% end %>
	        </div>
          </div>
        </div>
    </div>
    <div id="myModal1" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	    <div class="modal-dialog">
	      <div class="modal-content">
  		    <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	          <h4 class="modal-title" id="myModalLabel">Close Issue</h4>
	        </div>
	        <div class="container">
		        <%= form_for @request do |f| %>
		        	<div class="col-xs-3">
		        	<%= f.check_box :status, class: "form-control" %> 
		        	</div>
		    </div>
	        <div class="modal-footer">
	        	    <%= f.submit 'Update', class: 'btn btn-default btn-xs' %>
	        	<% end %>
	        </div>
          </div>
        </div>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <%= f.label :first_name %>
      <%= f.text_field :first_name , class: 'form-control' %><br>
      <%= f.label :last_name %>
      <%= f.text_field :last_name , class: 'form-control' %><br>
      <%= f.label :username %>
      <%= f.text_field :username , class: 'form-control' %><br>
      <%= f.label :password, "Password" %>
      <%= f.password_field :password , class: 'form-control' %><br>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
  <% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>New</th>
      <th>Show</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="col-md-6">
  <%= form_for [@user, @user.requests.build] do |f| %>
    <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
    </div>
    <%= f.submit 'submit', class: "btn btn-primary" %>
  <% end %>
</div>
<div class="col-md-6">
  <h2>Previous Requests</h2>
  <table class="table">
    <thead>
    </thead>
    <tbody>
      <% @requests.each do |r| %>
      <tr>
        <% if r.user_id == @user.id %>
        <td><%= r.title %></td>
        <td><%= r.description %></td>
        <td><%= r.status? ? "\u2713" : "\u2717"  %></td>
        <td><%= link_to "Show", request_path(r) %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<script>
var firefoxTestDone = false
function reportFirefoxTestResult(result) {
  if (!firefoxTestDone) {
    $('#ff-bug-test-result')
      .addClass(result ? 'text-success' : 'text-danger')
      .text(result ? 'PASS' : 'FAIL')  
  }
  firefoxTestDone = true
}

$(function () {
  $('.js-popover').popover()
  $('.js-tooltip').tooltip()
  $('#tall-toggle').click(function () {
    $('#tall').toggle()
  })
  $('#ff-bug-input').one('focus', function () {
    $('#myModal2').on('focus', function () {
      reportFirefoxTestResult(false)
    })
    $('#ff-bug-input').on('focus', function () {
      reportFirefoxTestResult(true)
    })
  })
})
</script>